spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/subscriptions/**
        - id: shopify-connector-service
          uri: lb://shopify-connector-service
          predicates:
            - Path=/shopify/**
        - id: qbo-connector-service
          uri: lb://qbo-connector-service
          predicates:
            - Path=/qbo/**
        - id: sync-core-service
          uri: lb://sync-core-service
          predicates:
            - Path=/connections/**
