INSERT INTO
    plans (
        code,
        name,
        max_connections,
        allowed_intervals,
        manual_sync_per_day,
        backfill_days,
        history_retention_days,
        searchable_history_days,
        billing_interval,
        price_amount,
        currency
    )
VALUES (
        'demo',
        'Demo',
        1,
        '{24}',
        1,
        30,
        90,
        30,
        'none',
        NULL,
        'USD'
    ),
    (
        'starter',
        'Starter',
        1,
        '{24}',
        1,
        30,
        90,
        30,
        'month',
        29.00,
        'USD'
    ),
    (
        'pro',
        'Pro',
        10,
        '{6,8,12,24}',
        5,
        180,
        365,
        90,
        'month',
        79.00,
        'USD'
    ),
    (
        'business',
        'Business',
        50,
        '{1,2,3,4,6,8,12,24}',
        -1,
        730,
        1095,
        1095,
        'month',
        199.00,
        'USD'
    );