server:
  port: 8761
spring:
  application:
    name: eureka-server
  config:
    import: "configserver:http://config-server:8888"
eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
